name: docker image ci

on:
  workflow_dispatch: #github页面手动触发
  push:
    branches:
      - dev

env:
  IMAGE_NAME: yangsendyx/wechat-bot

jobs:
#   get-tags:
#     runs-on: ubuntu-latest
#     env:
#       TZ: Asia/Shanghai
#     outputs:
#       tags: ${{ steps.output-id.outputs.v }}
#     steps:
#       - uses: actions/checkout@v3
#       - id: output-id
#         run: |
#           VERSION=dev
#           if [[ $GITHUB_REF == refs/tags/* ]]; then
#             VERSION=${GITHUB_REF#refs/tags/v}
#           fi
#           echo "v=${VERSION}" >> $GITHUB_OUTPUT

  push-ghcr:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      REGISTRY: ghcr.io
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=dev,enable=${{ github.ref == 'refs/heads/dev' }}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=pep440,pattern={{raw}},enable=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Build && Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
            windows/amd64
          #  build-args: |
            # COMMIT_SHA=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}